### ISSUE TITLE
Bump version and publish to npm

### ISSUE THREAD

**Issue by wbinnssmith** [atom/atom-select-list#17]
In order to avoid doing a `git clone` for this dependency in [command-palette#85](https://github.com/atom/command-palette/pull/85), this package should be published with a new version :)

Thanks!

**Comment by Ben3eeE** [comment]
@wbinnssmith Thanks, sorry that we missed this. I published 0.3.0 now.

**Comment by Ben3eeE** [comment]
I also published a new version of command-palette 0.41.1 ⚡️
