### ISSUE TITLE
Expose a setQuery method in SelectListView

### ISSUE THREAD

**Issue by sanketh95** [atom/atom-select-list#3]
Hi guys,

I feel it would be useful to provide a `setQuery` method to set the text in the internal `TextEditor`. Currently this can be done using

`selectListView.refs.queryEditor.setText`

This is not a good way to do it as it makes assumptions on the internals of the class. 

**Need**
This would provide more flexibility in how the functionality of select view can be used.

Let me know what you guys think.

Thanks,
Sanketh

**Comment by as-cii** [comment]
Thanks for your feedback, @sanketh95! 🙇 Starting from `atom-select-list@0.2.0` you can now update the select list view's query by doing something like the following:

```js
await selectListView.update({query: 'hello'})
console.log(selectListView.getQuery()) // ==> 'hello'
await selectListView.update({query: 'world'})
console.log(selectListView.getQuery()) // ==> 'world'
```

**Comment by sanketh95** [comment]
Awesome @as-cii !
